#!/bin/bash

egrep '(vmx|svm)' /proc/cpuinfo 2>&1 >/dev/null

if [ $? == 1 ]; then
  echo "Has virtualization been enabled?"
  exit 1
fi


if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
elif [ -f /etc/SuSe-release ]; then
    # Older SuSE/etc.
    ...
elif [ -f /etc/redhat-release ]; then
    # Older Red Hat, CentOS, etc.
    ...
else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=$(uname -s)
    VER=$(uname -r)
fi


if [ $OS == "Debian GNU/Linux" ] && [ $VER = "10" ]; then
  REQPKS="./debianpkgs.txt"
  PKGSTRING="apt install -y"
  PKGS=""
  while file= read -r line; do
    PKGS+="${line}"
  done < "$REQPKGS"
  $($PKGSTRING $PKGS)
  RESULT=$?
  if [ $RESULT == 0 ]; then
    echo "All packaged installed"
  fi
fi



#Add auto-config setup for libvirtd, ssh? and xenbr0

#Download Base images from hosting

#
